# Generated by Django 4.2a1 on 2023-02-13 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
