# Generated by Django 4.2b1 on 2023-03-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_photo_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="guests",
            field=models.IntegerField(help_text="How many people will be stayng?"),
        ),
    ]
